import { Question } from '@/types';

export const questions: Question[] = [
  {
    id: 1,
    question: '"Eu mereço ser feliz. Deus quer a minha felicidade."',
    options: [
      'Verdadeiro — Deus quer nossa felicidade',
      'Falso — Deus não liga pra nossa felicidade',
      'Parcialmente verdadeiro — Deus quer nossa santidade, e a felicidade vem como fruto',
      'Depende da situação',
    ],
    correct: 2,
    explanation: 'Deus se importa com nossa felicidade, mas o objetivo principal dele é nossa santidade. A felicidade verdadeira é consequência de viver em alinhamento com ele — não o ponto de partida.',
    verse: '1 Tessalonicenses 4:3 — "A vontade de Deus é a nossa santificação."',
    difficulty: 'medium',
  },
  {
    id: 2,
    question: '"Se o relacionamento não está te fazendo feliz, é porque não é de Deus."',
    options: [
      'Verdadeiro — Deus não colocaria algo ruim na sua vida',
      'Falso — todo relacionamento tem fases difíceis',
      'Verdadeiro — você precisa se sentir bem pra saber que é certo',
      'Falso — dificuldade não é sinal de que algo está errado',
    ],
    correct: 3,
    explanation: 'Dificuldade não é prova de que algo não é de Deus. Relacionamentos saudáveis exigem trabalho, paciência e crescimento. O desconforto às vezes é onde o caráter se forma.',
    verse: 'Romanos 5:3-4 — "A tribulação produz perseverança, a perseverança caráter."',
    difficulty: 'medium',
  },
  {
    id: 3,
    question: '"Perdoar significa esquecer e voltar a confiar como antes."',
    options: [
      'Verdadeiro',
      'Falso',
      'Verdadeiro — se você não esqueceu, não perdoou de verdade',
      'Depende',
    ],
    correct: 1,
    explanation: 'Perdão é uma decisão espiritual que você toma independente da outra pessoa. Confiança é algo que se reconstrói com tempo e atitudes concretas. Confundir os dois causa muito dano.',
    verse: 'Lucas 17:3-4 — "Se teu irmão pecar, repreende-o; e se ele se arrepender, perdoa-o."',
    difficulty: 'easy',
  },
  {
    id: 4,
    question: '"Honrar meus pais significa obedecer tudo que eles mandam, sempre."',
    options: [
      'Verdadeiro — Bíblia manda obedecer pai e mãe',
      'Falso — honra não é obediência cega',
      'Verdadeiro — questionar os pais é desonra',
      'Falso — você não deve nada aos seus pais',
    ],
    correct: 1,
    explanation: 'Honrar é tratar com respeito e consideração. Você pode discordar, expressar sua opinião com respeito, e ainda assim honrar. Obediência cega não é virtude — é ausência de discernimento.',
    verse: 'Efésios 6:1-2 — "Filhos, obedecei a vossos pais no Senhor, pois isto é justo."',
    difficulty: 'medium',
  },
  {
    id: 5,
    question: '"Amizade verdadeira é aquela que te aceita do jeito que você é, sem te julgar."',
    options: [
      'Verdadeiro — julgamento destrói amizade',
      'Falso — amizade verdadeira às vezes confronta',
      'Verdadeiro — só Deus pode julgar',
      'Depende do assunto',
    ],
    correct: 1,
    explanation: 'Aceitar uma pessoa não significa aceitar tudo que ela faz. Amigo de verdade fala a verdade mesmo quando dói — porque se importa com quem você está se tornando, não só com quem você é agora.',
    verse: 'Provérbios 27:6 — "Fiéis são as feridas do amigo."',
    difficulty: 'medium',
  },
  {
    id: 6,
    question: '"Se você realmente ama alguém, os ciúmes são normais e mostram que você se importa."',
    options: [
      'Verdadeiro',
      'Falso',
      'Verdadeiro — sem ciúme não há amor de verdade',
      'Falso — ciúme é sempre pecado',
    ],
    correct: 1,
    explanation: 'Ciúme possessivo não é amor — é insegurança e controle disfarçados. O amor bíblico confia, não controla. Querer monitorar, isolar ou limitar a pessoa que você ama é um sinal de alerta, não de devoção.',
    verse: '1 Coríntios 13:4-5 — "O amor é paciente... não se comporta inconvenientemente."',
    difficulty: 'easy',
  },
  {
    id: 7,
    question: '"Deus me criou assim, então tudo que sinto naturalmente deve ser bom."',
    options: [
      'Verdadeiro',
      'Falso',
      'Verdadeiro — sentimentos não mentem',
      'Depende do sentimento',
    ],
    correct: 1,
    explanation: 'Deus nos criou bons, mas a queda afetou nossa natureza. Sentimentos são reais mas não são sempre confiáveis como guia moral. A Bíblia nos chama a renovar a mente, não a seguir cada impulso natural.',
    verse: 'Jeremias 17:9 — "Enganoso é o coração, mais do que todas as coisas."',
    difficulty: 'hard',
  },
  {
    id: 8,
    question: '"Falar mal de alguém pros amigos não é fofoca se for verdade."',
    options: [
      'Verdadeiro',
      'Falso',
      'Verdadeiro — contar a verdade é sempre certo',
      'Depende de quem você conta',
    ],
    correct: 1,
    explanation: 'Fofoca não é definida pela veracidade da informação, mas pelo propósito de espalhá-la. Se você não faz parte do problema nem da solução, a informação não te pertence — verdadeira ou não.',
    verse: 'Provérbios 11:13 — "O que anda em mexerico descobre o segredo, mas o de espírito fiel o encobre."',
    difficulty: 'easy',
  },
  {
    id: 9,
    question: 'Izadora ajudou Kai várias vezes. Kai nunca retribui e some quando ela precisa. As amigas falam: "larga ele, você merece amigos melhores." O que Izadora deve fazer?',
    options: [
      'Reduzir o contato gradualmente sem criar drama',
      'Continuar ajudando sem cobrar nada — amor não guarda registro',
      'Conversar honestamente com Kai sobre o que tá sentindo',
      'Aceitar que nem toda amizade é recíproca e seguir em frente',
    ],
    correct: 2,
    explanation: 'Largar sem conversar parece saudável mas é evitação. O amor cristão é corajoso o suficiente pra falar a verdade antes de se afastar. Confronto honesto é um ato de amor, não de fraqueza.',
    verse: 'Mateus 18:15 — "Se teu irmão pecar contra ti, vai e repreende-o entre ti e ele só."',
    difficulty: 'medium',
  },
  {
    id: 10,
    question: 'Guilherme e Giullya namoram há 2 anos. Ela descobriu que ele ficou próximo demais de uma amiga mas ele jura que não aconteceu nada. Giullya não consegue confiar mais. As amigas falam: "se você perdoou, tem que confiar." Ela deve forçar a confiança de volta?',
    options: [
      'Sim — desconfiar depois de perdoar é falta de fé',
      'Não — confiança quebrada leva tempo e atitudes concretas pra reconstruir',
      'Sim — Deus restaura completamente quem entrega de verdade',
      'Não — se quebrou uma vez, nunca mais vai ser igual',
    ],
    correct: 1,
    explanation: 'Perdão é uma decisão espiritual. Confiança é um processo que depende de frutos reais. Giullya pode perdoar Guilherme completamente e ainda assim observar se ele é fiel no dia a dia. Isso não é falta de fé — é sabedoria.',
    verse: 'Lucas 16:10 — "Quem é fiel no mínimo, também é fiel no muito."',
    difficulty: 'hard',
  },
  {
    id: 11,
    question: 'Cauã descobriu que o pai dele tá tomando uma atitude errada em casa. A mãe pede pra ele não falar nada pra não piorar. O que Cauã deve fazer?',
    options: [
      'Respeitar o pedido da mãe — ela conhece melhor a dinâmica da família',
      'Falar com o pai diretamente — a verdade precisa ser dita',
      'Orar, esperar o momento certo e falar com respeito mesmo sendo difícil',
      'Buscar um adulto de confiança fora de casa pra orientar',
    ],
    correct: 2,
    explanation: 'Honrar os pais não significa silêncio eterno. Às vezes honrar é ter coragem de falar a verdade com amor, no momento certo, com o motivo certo. Discernimento é diferente de omissão.',
    verse: 'Efésios 4:15 — "Seguindo a verdade em amor, cresceremos em tudo."',
    difficulty: 'hard',
  },
  {
    id: 12,
    question: 'Layza perdoou Duda por uma traição séria de amizade. Duda mudou, pediu desculpa, tá diferente. Mas Layza ainda mantém distância. Pessoas da igreja falam que ela precisa restaurar a amizade completamente se perdoou de verdade.',
    options: [
      'Concordo — distância depois do perdão é amargura disfarçada',
      'Concordo — se Duda realmente mudou, Layza precisa corresponder',
      'Discordo — Layza pode perdoar e ainda escolher o nível de proximidade que quer ter',
      'Depende — o tempo vai mostrar se o perdão foi verdadeiro',
    ],
    correct: 2,
    explanation: 'Perdão liberta o coração da amargura. Reconstruir intimidade é uma escolha separada que depende de frutos e sabedoria, não de obrigação espiritual. Jesus perdoou Pedro e ainda assim redirecionou o relacionamento com propósito.',
    verse: 'Provérbios 4:23 — "Sobre tudo o que se deve guardar, guarda o teu coração."',
    difficulty: 'hard',
  },
  {
    id: 13,
    question: 'Murilo faz a vida de Yuri um inferno na escola. Um dia Murilo chega arrasado porque algo grave aconteceu na família. Os amigos de Yuri falam: "você não deve nada pra ele." O que Yuri deve fazer?',
    options: [
      'Ajudar só se Murilo pedir desculpa primeiro — responsabilidade precisa existir',
      'Ignorar — cada um colhe o que planta',
      'Ajudar sem precisar fingir que tá tudo bem entre eles',
      'Usar o momento pra se aproximar e tentar resolver as brigas antigas',
    ],
    correct: 2,
    explanation: 'O padrão cristão é mais radical que justiça proporcional. Yuri pode ajudar Murilo e ainda ter limites saudáveis com ele. Agir certo independente de merecimento, sem fingir que a dor não existe — isso é o amor de Cristo na prática.',
    verse: 'Romanos 12:20 — "Se o teu inimigo tiver fome, dá-lhe de comer."',
    difficulty: 'hard',
  },
  {
    id: 14,
    question: 'Guilherme e Giullya brigam muito mas quando tá bom, tá muito bom. Ele sempre pede desculpa depois das brigas. As amigas falam que relacionamento tem altos e baixos. A mãe de Giullya fala que sempre foi assim com o pai dela.',
    options: [
      'As amigas têm razão — conflito faz parte de qualquer relacionamento',
      'A mãe tem mais experiência de vida, provavelmente sabe o que é normal',
      'O ciclo frequente de briga intensa seguida de reconciliação pode indicar um padrão destrutivo',
      'Se ele sempre pede desculpa, é sinal de que se importa e quer melhorar',
    ],
    correct: 2,
    explanation: 'Conflito é normal — ciclo de explosão e reconciliação intensa não é. Pedir desculpa é bom mas não substitui mudança de padrão. O amor bíblico é consistente e estável, não uma montanha-russa emocional.',
    verse: '1 Coríntios 13:5 — "O amor não se comporta inconvenientemente, não se irrita."',
    difficulty: 'hard',
  },
  {
    id: 15,
    question: 'Calebe discorda de algo que o líder da igreja ensinou. Ele acha que o líder errou biblicamente. O que Calebe deve fazer?',
    options: [
      'Estudar mais antes de questionar — humildade exige isso',
      'Assumir que entendeu errado — o líder tem mais anos de experiência',
      'Conversar com outros da igreja pra ver se mais alguém sentiu o mesmo',
      'Estudar, buscar referências, e se tiver convicto, conversar com o líder em privado com respeito',
    ],
    correct: 3,
    explanation: 'Submissão bíblica é à Palavra, não à pessoa. Os bereanos checavam tudo nas Escrituras mesmo com Paulo. Questionar com respeito, em privado, com fundamento bíblico não é falta de honra — é maturidade espiritual.',
    verse: 'Atos 17:11 — "Examinavam as Escrituras cada dia para ver se estas coisas eram assim."',
    difficulty: 'hard',
  },
  {
    id: 16,
    question: 'Juan viu Davi falando mal de Miguel nas costas. Juan é amigo dos dois. O que ele deve fazer?',
    options: [
      'Fingir que não ouviu — não é problema dele',
      'Contar pra Miguel o que Davi falou — ele merece saber',
      'Falar com Davi primeiro sobre o que ele ouviu',
      'Ficar de olho pra ver se vira um padrão antes de agir',
    ],
    correct: 2,
    explanation: 'Contar pra Miguel parece leal mas espalha o conflito. Ir à fonte primeiro é mais difícil e menos dramático — mas tenta preservar as duas amizades em vez de inflamar a situação.',
    verse: 'Provérbios 11:13 — "O que anda em mexerico descobre o segredo, mas o de espírito fiel o encobre."',
    difficulty: 'medium',
  },
  {
    id: 17,
    question: 'Cauã gosta de Vitória (Celso) mas tem medo de ser rejeitado. Os amigos falam que ele deve mandar mensagem pelo Instagram pra não ser tão direto. O que Cauã deve fazer?',
    options: [
      'Mandar mensagem — é mais seguro e menos constrangedor',
      'Pedir pra uma amiga em comum sondar antes',
      'Esperar ela dar sinal primeiro pra ter mais certeza',
      'Ser honesto e direto com ela pessoalmente, aceitando que a resposta pode ser não',
    ],
    correct: 3,
    explanation: 'O mundo valoriza estratégia pra minimizar risco emocional. O valor cristão é integridade e coragem. Ser direto mesmo com risco de rejeição é mais alinhado com o caráter de Cristo do que manobrar a situação pra se proteger.',
    verse: '2 Timóteo 1:7 — "Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio."',
    difficulty: 'medium',
  },
  {
    id: 18,
    question: 'Daniel e Lucas são melhores amigos. Lucas começou a namorar e sumiu completamente. Daniel tá magoado. O que Daniel deve fazer?',
    options: [
      'Respeitar — namorar muda as prioridades e é normal',
      'Postar sobre amizade nas redes sociais pra Lucas entender o recado',
      'Falar diretamente com Lucas sobre como tá se sentindo',
      'Começar a se afastar também — quem não é visto não é lembrado',
    ],
    correct: 2,
    explanation: 'A parece madura mas é passividade — Daniel engole a mágoa sem comunicar. Amizade verdadeira tem voz. Falar o que sente com honestidade é um ato de amor, não fraqueza.',
    verse: 'Provérbios 27:17 — "O ferro com ferro se afia, e o homem com o seu amigo."',
    difficulty: 'medium',
  },
];

export function getQuestionsByDifficulty(difficulty: 'easy' | 'medium' | 'hard') {
  return questions.filter(q => q.difficulty === difficulty);
}

// Roulette questions - verbal response only, more open-ended
export const rouletteQuestions = {
  easy: [
    'Seu amigo te conta um segredo e pede pra não falar pra ninguém. Depois você descobre que outras pessoas já sabem. Você ainda é obrigado a guardar o segredo?',
    'Você brigou com seu melhor amigo e os dois ficaram sem se falar. Quem deve dar o primeiro passo?',
    'Seu pai pediu pra você fazer algo que você não concorda. O que você faz?',
    'Você viu alguém da igreja falando mal de outra pessoa. Você conhece os dois. O que você faz?',
    'Seu amigo tá em um relacionamento que você acha que não faz bem pra ele. Você fala ou fica quieto?',
    'Você gosta de alguém mas tem medo de ser rejeitado. O que a Bíblia te diria sobre esse medo?',
    'Alguém te magoou e pediu desculpa. Você perdoou. Mas ainda não confia nessa pessoa. Isso é errado?',
  ],
  medium: [
    'Você tá namorando e seu parceiro fica com ciúme de todo mundo que você conversa. Ele diz que é porque te ama muito. Isso é amor?',
    'Seu amigo fez algo errado e você é o único que sabe. Ele pede pra você não contar. Mas a atitude dele tá machucando outra pessoa. O que você faz?',
    'Você discorda de algo que seu líder ensinou na igreja. O que você faz?',
    'Você perdoou alguém que te traiu mas as pessoas da igreja falam que você precisa restaurar a amizade completamente. Você é obrigado?',
    'Seu namorado ou namorada fala que você precisa escolher entre ele e seus amigos. O que isso te diz sobre o relacionamento?',
    'Você vê nas redes sociais que trair é normalizado, que ciúme é amor, que ser frio é cool. Como você decide o que é certo?',
    'Alguém que você não gosta precisou de ajuda. Você ajudou, mas no fundo ficou com raiva. Isso conta como amor ao próximo?',
  ],
  hard: [
    'A Bíblia fala pra amar o próximo como a si mesmo. Mas e se você não se ama? Como você ama o próximo?',
    'Qual a diferença entre perdoar alguém e reconciliar com alguém? A Bíblia exige os dois?',
    'Por que seguir os valores bíblicos num relacionamento é diferente de simplesmente ser uma boa pessoa?',
    'Se Deus é amor, por que ele tem padrões tão específicos sobre relacionamentos? Isso não é contraditório?',
    'O Antigo Testamento tem figuras que erraram feio nos relacionamentos — Davi, Sansão, Salomão. Por que Deus usou essas pessoas mesmo assim?',
    'Você tem o Espírito Santo, a Bíblia, e acesso a Deus. O que te impede de tomar decisões melhores nos seus relacionamentos?',
  ],
};
